const db = require('./db');
const { initSchema } = require('./schema');

function seedGovtData() {
  initSchema();

  console.log('[Govt Seed] Checking and seeding Government Registries...');

  // 1. RIVERS AND DAMS DATASET (CWC / India-WRIS)
  const riversCount = db.prepare('SELECT count(*) as count FROM rivers_and_dams').get().count;
  if (riversCount === 0) {
    const riversDamsData = [
      {
        name: 'Ganga River (Upper & Middle Basin)',
        type: 'River',
        river_basin: 'Ganga Basin',
        state: 'Uttarakhand / Uttar Pradesh / Bihar / West Bengal',
        district: 'Haridwar to Murshidabad',
        latitude: 29.9457,
        longitude: 78.1642,
        length_km: 2525,
        avg_depth_m: 16.5,
        max_monsoon_depth_m: 32.0,
        catchment_area_sqkm: 861404,
        danger_water_level_m: 71.26,
        current_water_level_m: 69.85,
        full_reservoir_level_m: 0,
        maximum_water_level_m: 0,
        live_storage_capacity_mcm: 0,
        current_storage_pct: 0,
        spillway_capacity_cusecs: 0,
        cwc_monitoring_status: 'Telemetry Active • Near Warning Level',
        historical_breach_disasters: 'Annual seasonal monsoon inundation affecting millions across Varanasi, Patna, and Malda embankments.',
        downstream_hazard_level: 'High'
      },
      {
        name: 'Tehri Dam & Hydroelectric Reservoir',
        type: 'Dam',
        river_basin: 'Bhagirathi / Ganga Basin',
        state: 'Uttarakhand',
        district: 'Tehri Garhwal',
        latitude: 30.3781,
        longitude: 78.4803,
        length_km: 0.575,
        avg_depth_m: 260.5,
        max_monsoon_depth_m: 265.0,
        catchment_area_sqkm: 7511,
        danger_water_level_m: 830.0,
        current_water_level_m: 818.5,
        full_reservoir_level_m: 830.0,
        maximum_water_level_m: 835.0,
        live_storage_capacity_mcm: 2615,
        current_storage_pct: 78.4,
        spillway_capacity_cusecs: 15540,
        cwc_monitoring_status: 'Automated Inflow Monitoring • Stable',
        historical_breach_disasters: 'High seismic zone V location. Poses downstream flood alert risk for Rishikesh, Haridwar, and Roorkee plains if rim failure occurs.',
        downstream_hazard_level: 'Critical'
      },
      {
        name: 'Alaknanda River Gorge Corridor',
        type: 'River',
        river_basin: 'Alaknanda / Upper Ganga',
        state: 'Uttarakhand',
        district: 'Chamoli / Rudraprayag',
        latitude: 30.5580,
        longitude: 79.5695,
        length_km: 195,
        avg_depth_m: 8.5,
        max_monsoon_depth_m: 24.0,
        catchment_area_sqkm: 11000,
        danger_water_level_m: 1150.0,
        current_water_level_m: 1146.8,
        full_reservoir_level_m: 0,
        maximum_water_level_m: 0,
        live_storage_capacity_mcm: 0,
        current_storage_pct: 0,
        spillway_capacity_cusecs: 0,
        cwc_monitoring_status: 'Extreme Gradient Telemetry Active',
        historical_breach_disasters: '1970 Belakuchi rockslide dam breach flood; 2021 Rishiganga-Tapovan flash surge causing 204 casualties.',
        downstream_hazard_level: 'Critical'
      },
      {
        name: 'Brahmaputra River Mega-Basin',
        type: 'River',
        river_basin: 'Brahmaputra Basin',
        state: 'Assam / Arunachal Pradesh',
        district: 'Dibrugarh / Majuli / Guwahati',
        latitude: 26.1856,
        longitude: 91.7486,
        length_km: 916,
        avg_depth_m: 38.0,
        max_monsoon_depth_m: 120.0,
        catchment_area_sqkm: 580000,
        danger_water_level_m: 49.68,
        current_water_level_m: 49.92,
        full_reservoir_level_m: 0,
        maximum_water_level_m: 0,
        live_storage_capacity_mcm: 0,
        current_storage_pct: 0,
        spillway_capacity_cusecs: 0,
        cwc_monitoring_status: 'RED ALERT • Surpassing Danger Level',
        historical_breach_disasters: 'Consumes 4.27 lakh hectares through chronic bank erosion. 1950 earthquake altered riverbed elevation by 3m; 2022 flood displaced 4 million.',
        downstream_hazard_level: 'Critical'
      },
      {
        name: 'Teesta River & Chungthang GLOF Corridor',
        type: 'River',
        river_basin: 'Teesta / Brahmaputra Sub-basin',
        state: 'Sikkim / West Bengal',
        district: 'Mangan / Kalimpong / Jalpaiguri',
        latitude: 27.6041,
        longitude: 88.6465,
        length_km: 414,
        avg_depth_m: 6.0,
        max_monsoon_depth_m: 18.5,
        catchment_area_sqkm: 12540,
        danger_water_level_m: 1540.0,
        current_water_level_m: 1538.2,
        full_reservoir_level_m: 0,
        maximum_water_level_m: 0,
        live_storage_capacity_mcm: 0,
        current_storage_pct: 0,
        spillway_capacity_cusecs: 0,
        cwc_monitoring_status: 'High Alert • Glacial Lake Surveillance Active',
        historical_breach_disasters: 'Oct 2023 South Lhonak Glacial Lake Outburst Flood (GLOF) completely destroyed the Chungthang Dam (Teesta-III) and killed 179 people.',
        downstream_hazard_level: 'Critical'
      },
      {
        name: 'Chungthang Dam (Teesta-III Hydro Project)',
        type: 'Dam',
        river_basin: 'Teesta Basin',
        state: 'Sikkim',
        district: 'Mangan',
        latitude: 27.6042,
        longitude: 88.6468,
        length_km: 0.120,
        avg_depth_m: 60.0,
        max_monsoon_depth_m: 65.0,
        catchment_area_sqkm: 3800,
        danger_water_level_m: 1545.0,
        current_water_level_m: 0,
        full_reservoir_level_m: 1545.0,
        maximum_water_level_m: 1548.0,
        live_storage_capacity_mcm: 5.1,
        current_storage_pct: 0,
        spillway_capacity_cusecs: 7000,
        cwc_monitoring_status: 'CATASTROPHIC BREACH LOGGED (Oct 2023)',
        historical_breach_disasters: '60m high concrete gravity dam washed away in under 12 minutes following upstream GLOF surge, wiping out military bases and downstream towns.',
        downstream_hazard_level: 'Critical'
      },
      {
        name: 'Mullaperiyar Dam',
        type: 'Dam',
        river_basin: 'Periyar River Basin',
        state: 'Kerala (Operated by Tamil Nadu)',
        district: 'Idukki',
        latitude: 9.5294,
        longitude: 77.1422,
        length_km: 0.365,
        avg_depth_m: 53.6,
        max_monsoon_depth_m: 55.0,
        catchment_area_sqkm: 647,
        danger_water_level_m: 43.28,
        current_water_level_m: 42.15,
        full_reservoir_level_m: 43.28,
        maximum_water_level_m: 46.33,
        live_storage_capacity_mcm: 443.2,
        current_storage_pct: 88.6,
        spillway_capacity_cusecs: 3462,
        cwc_monitoring_status: 'Special Supervisory Committee Watch',
        historical_breach_disasters: '130-year-old lime-surkhi masonry structure situated in active seismic zone. Catastrophic risk to 3.5 million citizens across 5 districts downstream.',
        downstream_hazard_level: 'Critical'
      },
      {
        name: 'Idukki Double Curvature Arch Dam',
        type: 'Dam',
        river_basin: 'Periyar River Basin',
        state: 'Kerala',
        district: 'Idukki',
        latitude: 9.8436,
        longitude: 76.9744,
        length_km: 0.365,
        avg_depth_m: 168.9,
        max_monsoon_depth_m: 170.0,
        catchment_area_sqkm: 649,
        danger_water_level_m: 732.43,
        current_water_level_m: 728.12,
        full_reservoir_level_m: 732.43,
        maximum_water_level_m: 734.0,
        live_storage_capacity_mcm: 1460,
        current_storage_pct: 81.2,
        spillway_capacity_cusecs: 5012,
        cwc_monitoring_status: 'Normal Dynamic Level Control',
        historical_breach_disasters: 'All 5 Cheruthoni shutters opened simultaneously during August 2018 deluge after 26 years, creating major flash flood across Periyar valley.',
        downstream_hazard_level: 'High'
      },
      {
        name: 'Beas River Torrent & Mountain Basin',
        type: 'River',
        river_basin: 'Indus / Beas Basin',
        state: 'Himachal Pradesh / Punjab',
        district: 'Kullu / Mandi / Kangra',
        latitude: 31.9579,
        longitude: 77.1095,
        length_km: 470,
        avg_depth_m: 4.8,
        max_monsoon_depth_m: 16.2,
        catchment_area_sqkm: 20303,
        danger_water_level_m: 780.0,
        current_water_level_m: 776.4,
        full_reservoir_level_m: 0,
        maximum_water_level_m: 0,
        live_storage_capacity_mcm: 0,
        current_storage_pct: 0,
        spillway_capacity_cusecs: 0,
        cwc_monitoring_status: 'Monsoon Flash Surge Alert Zone',
        historical_breach_disasters: 'July 2023 unprecedented cloudburst discharge (1.5 lakh cusecs) washed away Chandigarh-Manali NH-21, Pandoh market, and 24 bridges.',
        downstream_hazard_level: 'Critical'
      },
      {
        name: 'Bhakra Nangal Concrete Gravity Dam',
        type: 'Dam',
        river_basin: 'Sutlej / Indus Basin',
        state: 'Himachal Pradesh / Punjab',
        district: 'Bilaspur',
        latitude: 31.4116,
        longitude: 76.4363,
        length_km: 0.518,
        avg_depth_m: 226.0,
        max_monsoon_depth_m: 228.0,
        catchment_area_sqkm: 56874,
        danger_water_level_m: 512.06,
        current_water_level_m: 504.15,
        full_reservoir_level_m: 512.06,
        maximum_water_level_m: 515.11,
        live_storage_capacity_mcm: 6880,
        current_storage_pct: 74.3,
        spillway_capacity_cusecs: 8212,
        cwc_monitoring_status: 'High Automated Regulation • Stable',
        historical_breach_disasters: '1988 severe monsoon un-regulated spillway discharge caused catastrophic inundation across 65% of Punjab agricultural plains.',
        downstream_hazard_level: 'High'
      },
      {
        name: 'Hirakud Earthen Dam',
        type: 'Dam',
        river_basin: 'Mahanadi Basin',
        state: 'Odisha',
        district: 'Sambalpur',
        latitude: 21.5700,
        longitude: 83.8700,
        length_km: 25.8,
        avg_depth_m: 61.0,
        max_monsoon_depth_m: 64.0,
        catchment_area_sqkm: 83400,
        danger_water_level_m: 192.02,
        current_water_level_m: 189.45,
        full_reservoir_level_m: 192.02,
        maximum_water_level_m: 192.63,
        live_storage_capacity_mcm: 5818,
        current_storage_pct: 69.8,
        spillway_capacity_cusecs: 42475,
        cwc_monitoring_status: 'CWC Telemetry Active • Controlled Discharge',
        historical_breach_disasters: '2011 severe delta flooding when 59 sluice gates were opened, inundating Cuttack, Kendrapara, and Puri delta habitations.',
        downstream_hazard_level: 'High'
      },
      {
        name: 'Sardar Sarovar Dam',
        type: 'Dam',
        river_basin: 'Narmada Basin',
        state: 'Gujarat',
        district: 'Narmada',
        latitude: 21.8290,
        longitude: 73.7486,
        length_km: 1.210,
        avg_depth_m: 163.0,
        max_monsoon_depth_m: 165.0,
        catchment_area_sqkm: 88000,
        danger_water_level_m: 138.68,
        current_water_level_m: 134.20,
        full_reservoir_level_m: 138.68,
        maximum_water_level_m: 140.21,
        live_storage_capacity_mcm: 5800,
        current_storage_pct: 79.1,
        spillway_capacity_cusecs: 84950,
        cwc_monitoring_status: 'Integrated River Basin Telemetry',
        historical_breach_disasters: 'Sept 2023 massive flash release (18.6 lakh cusecs) inundated downstream Bharuch and Ankleshwar habitations without timely Siren warnings.',
        downstream_hazard_level: 'High'
      },
      {
        name: 'Machchhu-II Earthen Dam (Historical Failure Site)',
        type: 'Dam',
        river_basin: 'Machchhu Basin',
        state: 'Gujarat',
        district: 'Morbi',
        latitude: 22.7562,
        longitude: 70.8988,
        length_km: 4.02,
        avg_depth_m: 26.0,
        max_monsoon_depth_m: 28.0,
        catchment_area_sqkm: 1928,
        danger_water_level_m: 57.0,
        current_water_level_m: 52.4,
        full_reservoir_level_m: 57.0,
        maximum_water_level_m: 58.2,
        live_storage_capacity_mcm: 110,
        current_storage_pct: 62.0,
        spillway_capacity_cusecs: 6200,
        cwc_monitoring_status: 'Reconstructed Post-1979 • Monitored',
        historical_breach_disasters: '11 August 1979: World\'s worst dam failure. Overtopping destroyed earthen walls, sending 30ft water wall into Morbi, drowning between 2,000 and 10,000 citizens.',
        downstream_hazard_level: 'High'
      },
      {
        name: 'Farakka Barrage Inter-State Corridor',
        type: 'Barrage',
        river_basin: 'Ganga / Padma Basin',
        state: 'West Bengal',
        district: 'Murshidabad',
        latitude: 24.8056,
        longitude: 87.9250,
        length_km: 2.24,
        avg_depth_m: 12.0,
        max_monsoon_depth_m: 19.5,
        catchment_area_sqkm: 840000,
        danger_water_level_m: 22.25,
        current_water_level_m: 21.80,
        full_reservoir_level_m: 22.25,
        maximum_water_level_m: 22.50,
        live_storage_capacity_mcm: 120,
        current_storage_pct: 85.0,
        spillway_capacity_cusecs: 76000,
        cwc_monitoring_status: 'Transboundary Indo-Bangladesh Watch',
        historical_breach_disasters: 'Chronic sand deposition and upstream backwater siltation causes severe bank erosion in Malda (Bhutan-Ganga feeder) and transboundary tensions.',
        downstream_hazard_level: 'Medium'
      }
    ];

    const insertRiver = db.prepare(`
      INSERT INTO rivers_and_dams (
        name, type, river_basin, state, district, latitude, longitude,
        length_km, avg_depth_m, max_monsoon_depth_m, catchment_area_sqkm,
        danger_water_level_m, current_water_level_m, full_reservoir_level_m,
        maximum_water_level_m, live_storage_capacity_mcm, current_storage_pct,
        spillway_capacity_cusecs, cwc_monitoring_status, historical_breach_disasters,
        downstream_hazard_level
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    for (const r of riversDamsData) {
      insertRiver.run(
        r.name, r.type, r.river_basin, r.state, r.district, r.latitude, r.longitude,
        r.length_km, r.avg_depth_m, r.max_monsoon_depth_m, r.catchment_area_sqkm,
        r.danger_water_level_m, r.current_water_level_m, r.full_reservoir_level_m,
        r.maximum_water_level_m, r.live_storage_capacity_mcm, r.current_storage_pct,
        r.spillway_capacity_cusecs, r.cwc_monitoring_status, r.historical_breach_disasters,
        r.downstream_hazard_level
      );
    }
    console.log(`[Govt Seed] Seeded ${riversDamsData.length} Rivers and Dams records.`);
  }

  // 2. MINING SITES & DISASTERS DATASET (IBM / Ministry of Mines / Coal India)
  const miningCount = db.prepare('SELECT count(*) as count FROM mining_sites').get().count;
  if (miningCount === 0) {
    const miningSitesData = [
      {
        mine_name: 'Jharia Coalfield & Fire Pits (BCCL)',
        mineral_type: 'Coking Coal',
        operator_type: 'Government PSU',
        operating_agency: 'Bharat Coking Coal Ltd (Coal India Subsidiary)',
        state: 'Jharkhand',
        district: 'Dhanbad',
        latitude: 23.7431,
        longitude: 86.4132,
        mining_method: 'Opencast & Underground',
        production_capacity_mtpa: 36.5,
        lease_area_ha: 45000,
        tailings_pond_count: 8,
        tailings_failure_risk: 'High',
        ground_subsidence_risk: 'Critical',
        blast_vibration_impact_radius_km: 5.0,
        disaster_faced_by_locals: '70+ perpetual underground coal seam fires since 1916. Over 100,000 residents suffer severe structural house collapse, toxic CO/SO2 poisoning, and involuntary displacement.',
        underground_fire_status: 'Active Seam Fires (Blazing)',
        nearby_habitations_at_risk: 125000,
        compliance_status: 'DGMS High-Hazard Warning Zone'
      },
      {
        mine_name: 'Rajmahal OCP (Lalmatia Coal Mine)',
        mineral_type: 'Thermal Coal',
        operator_type: 'Government PSU',
        operating_agency: 'Eastern Coalfields Ltd (ECL / Coal India)',
        state: 'Jharkhand',
        district: 'Godda',
        latitude: 25.0489,
        longitude: 87.3524,
        mining_method: 'Opencast',
        production_capacity_mtpa: 17.0,
        lease_area_ha: 2200,
        tailings_pond_count: 4,
        tailings_failure_risk: 'High',
        ground_subsidence_risk: 'High',
        blast_vibration_impact_radius_km: 3.5,
        disaster_faced_by_locals: '29 Dec 2016 Catastrophic Overburden Dump Collapse: 350-meter rock dump slid into active pit, burying 23 workers and crushing equipment. Heavy dust blankets surrounding Santhal villages.',
        underground_fire_status: 'None',
        nearby_habitations_at_risk: 18500,
        compliance_status: 'DGMS Post-Accident Restructured'
      },
      {
        mine_name: 'Parsa East & Kente Basan (PEKB) Coal Block',
        mineral_type: 'Thermal Coal',
        operator_type: 'Private Lease',
        operating_agency: 'Adani Enterprises Ltd (MDO for RRVUNL)',
        state: 'Chhattisgarh',
        district: 'Surguja / Hasdeo Arand',
        latitude: 22.8420,
        longitude: 82.8050,
        mining_method: 'Opencast',
        production_capacity_mtpa: 15.0,
        lease_area_ha: 1898,
        tailings_pond_count: 3,
        tailings_failure_risk: 'Moderate',
        ground_subsidence_risk: 'Moderate',
        blast_vibration_impact_radius_km: 4.0,
        disaster_faced_by_locals: 'Clearance of dense Hasdeo Arand sal forests (300,000+ trees felled), loss of indigenous Gond tribal gathering lands, severe increase in human-elephant conflicts and perennial stream drying.',
        underground_fire_status: 'None',
        nearby_habitations_at_risk: 12000,
        compliance_status: 'NGT / MOEFCC Scrutiny Ongoing'
      },
      {
        mine_name: 'Sukinda Chromite Valley Mines',
        mineral_type: 'Chromite Ore',
        operator_type: 'Private Lease',
        operating_agency: 'Tata Steel Mining & Odisha Mining Corp (OMC)',
        state: 'Odisha',
        district: 'Jajpur / Keonjhar',
        latitude: 21.0267,
        longitude: 85.8056,
        mining_method: 'Opencast & Deep Pit',
        production_capacity_mtpa: 4.8,
        lease_area_ha: 4200,
        tailings_pond_count: 6,
        tailings_failure_risk: 'High',
        ground_subsidence_risk: 'Moderate',
        blast_vibration_impact_radius_km: 3.0,
        disaster_faced_by_locals: 'Un-treated overburden runoff exposes 2.6 million people to cancer-causing Hexavalent Chromium [Cr(VI)] in Brahmani river sub-basin. Chronic gastrointestinal and skin diseases in 28 villages.',
        underground_fire_status: 'None',
        nearby_habitations_at_risk: 42000,
        compliance_status: 'Pollution Control Board Remediated'
      },
      {
        mine_name: 'East Jaintia Rat-Hole Coal Fields',
        mineral_type: 'Anthracite Coal',
        operator_type: 'Private Lease',
        operating_agency: 'Unregulated Private Syndicates / Artisanal',
        state: 'Meghalaya',
        district: 'East Jaintia Hills',
        latitude: 25.3262,
        longitude: 92.3689,
        mining_method: 'Artisanal/Rat-Hole',
        production_capacity_mtpa: 2.2,
        lease_area_ha: 3500,
        tailings_pond_count: 0,
        tailings_failure_risk: 'Critical',
        ground_subsidence_risk: 'Critical',
        blast_vibration_impact_radius_km: 1.5,
        disaster_faced_by_locals: 'Dec 2018 Ksan disaster: 15 miners trapped and drowned 370 feet underground in flooded pit. Acid Mine Drainage (AMD) turned Lukha and Myntdu rivers toxic orange, destroying fish stocks.',
        underground_fire_status: 'None',
        nearby_habitations_at_risk: 14000,
        compliance_status: 'NGT Ban Violations Tracked'
      },
      {
        mine_name: 'Singrauli Thermal Coal & Ash Dykes',
        mineral_type: 'Coal & Heavy Fly Ash',
        operator_type: 'Government PSU',
        operating_agency: 'Northern Coalfields Ltd (NCL / NTPC)',
        state: 'Madhya Pradesh / Uttar Pradesh',
        district: 'Singrauli / Sonbhadra',
        latitude: 24.1997,
        longitude: 82.6644,
        mining_method: 'Opencast',
        production_capacity_mtpa: 42.0,
        lease_area_ha: 12500,
        tailings_pond_count: 12,
        tailings_failure_risk: 'Critical',
        ground_subsidence_risk: 'High',
        blast_vibration_impact_radius_km: 4.5,
        disaster_faced_by_locals: 'Repeated ash dyke breaches (Oct 2019, April 2020) flooded Rihand reservoir and agricultural lands with 35 lakh tons of heavy toxic ash slurry, killing 6 villagers and destroying crops.',
        underground_fire_status: 'Low',
        nearby_habitations_at_risk: 65000,
        compliance_status: 'NGT Monitoring Committee Monitored'
      },
      {
        mine_name: 'Bailadila Iron Ore Complex',
        mineral_type: 'High-Grade Hematite Iron Ore',
        operator_type: 'Government PSU',
        operating_agency: 'National Mineral Development Corporation (NMDC)',
        state: 'Chhattisgarh',
        district: 'Dantewada',
        latitude: 18.6667,
        longitude: 81.2500,
        mining_method: 'Opencast Ridge Top',
        production_capacity_mtpa: 28.0,
        lease_area_ha: 3800,
        tailings_pond_count: 5,
        tailings_failure_risk: 'Moderate',
        ground_subsidence_risk: 'Moderate',
        blast_vibration_impact_radius_km: 3.0,
        disaster_faced_by_locals: 'Fine red iron ore slime runoff turned Sankani and Dankani rivers deep crimson, rendering water unfit for cattle and agriculture across 40 tribal villages.',
        underground_fire_status: 'None',
        nearby_habitations_at_risk: 26000,
        compliance_status: 'IBM Zero Waste Guidelines Followed'
      },
      {
        mine_name: 'Jaduguda Uranium Mine & Tailings Pond',
        mineral_type: 'Uranium Ore',
        operator_type: 'Government PSU',
        operating_agency: 'Uranium Corporation of India Ltd (UCIL)',
        state: 'Jharkhand',
        district: 'East Singhbhum',
        latitude: 22.6500,
        longitude: 86.3500,
        mining_method: 'Underground Deep Shaft',
        production_capacity_mtpa: 0.8,
        lease_area_ha: 1200,
        tailings_pond_count: 3,
        tailings_failure_risk: 'High',
        ground_subsidence_risk: 'Low',
        blast_vibration_impact_radius_km: 2.0,
        disaster_faced_by_locals: 'Radioactive tailings slurry leakage into Subarnarekha river tributaries; civil rights reports documented elevated congenital deformities and miscarriages among nearby Adivasi settlements.',
        underground_fire_status: 'None',
        nearby_habitations_at_risk: 16000,
        compliance_status: 'AERB (Atomic Energy Regulatory Board) Regulated'
      },
      {
        mine_name: 'Bellary Iron Ore Scraping Concessions',
        mineral_type: 'Iron Ore / Manganese',
        operator_type: 'Private Lease',
        operating_agency: 'Multiple Private Concessionaires',
        state: 'Karnataka',
        district: 'Ballari / Vijayanagara',
        latitude: 15.1394,
        longitude: 76.9214,
        mining_method: 'Opencast Hillside',
        production_capacity_mtpa: 18.0,
        lease_area_ha: 6500,
        tailings_pond_count: 7,
        tailings_failure_risk: 'Moderate',
        ground_subsidence_risk: 'Moderate',
        blast_vibration_impact_radius_km: 3.5,
        disaster_faced_by_locals: 'Lokayukta investigation unmasked massive over-mining stripping entire mountain crests, severe groundwater depletion, and red dust pneumoconiosis in Sandur valley.',
        underground_fire_status: 'None',
        nearby_habitations_at_risk: 38000,
        compliance_status: 'Supreme Court CEC Monitored'
      },
      {
        mine_name: 'Makrana White Marble Quarry Belt',
        mineral_type: 'Calcite Marble',
        operator_type: 'Private Lease',
        operating_agency: 'Makrana Marble Small Scale Consortium',
        state: 'Rajasthan',
        district: 'Didwana-Kuchaman / Nagaur',
        latitude: 27.0422,
        longitude: 74.7258,
        mining_method: 'Deep Opencast Pit',
        production_capacity_mtpa: 3.5,
        lease_area_ha: 1500,
        tailings_pond_count: 2,
        tailings_failure_risk: 'Low',
        ground_subsidence_risk: 'High',
        blast_vibration_impact_radius_km: 2.0,
        disaster_faced_by_locals: '120m deep sheer-wall quarry pits directly adjoining high-density urban residential wards, causing foundation cracking, pit-wall collapses during monsoons, and airborne silica haze.',
        underground_fire_status: 'None',
        nearby_habitations_at_risk: 22000,
        compliance_status: 'State Mines Dept Regulated'
      }
    ];

    const insertMining = db.prepare(`
      INSERT INTO mining_sites (
        mine_name, mineral_type, operator_type, operating_agency, state,
        district, latitude, longitude, mining_method, production_capacity_mtpa,
        lease_area_ha, tailings_pond_count, tailings_failure_risk, ground_subsidence_risk,
        blast_vibration_impact_radius_km, disaster_faced_by_locals, underground_fire_status,
        nearby_habitations_at_risk, compliance_status
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    for (const m of miningSitesData) {
      insertMining.run(
        m.mine_name, m.mineral_type, m.operator_type, m.operating_agency, m.state,
        m.district, m.latitude, m.longitude, m.mining_method, m.production_capacity_mtpa,
        m.lease_area_ha, m.tailings_pond_count, m.tailings_failure_risk, m.ground_subsidence_risk,
        m.blast_vibration_impact_radius_km, m.disaster_faced_by_locals, m.underground_fire_status,
        m.nearby_habitations_at_risk, m.compliance_status
      );
    }
    console.log(`[Govt Seed] Seeded ${miningSitesData.length} Mining Sites records.`);
  }

  // 3. 20-YEAR HISTORICAL DISASTER ARCHIVE (2004 - 2024+)
  const disaster20Count = db.prepare('SELECT count(*) as count FROM historical_disasters_20yr').get().count;
  if (disaster20Count === 0) {
    const historicalDisasters = [
      {
        event_title: 'Wayanad Chooralmala & Mundakkai Double Debris Avalanche',
        disaster_category: 'Landslide / Debris Flow',
        primary_cause: 'Extreme Orographic Monsoon Rainfall (572 mm in 48h) + Pore-Water Saturation',
        year: 2024,
        date_occurred: '2024-07-30',
        state_country: 'Kerala (India)',
        district_region: 'Wayanad (Meppadi / Chooralmala / Mundakkai)',
        latitude: 11.5385,
        longitude: 76.1820,
        casualties_count: 428,
        displaced_population: 9800,
        economic_damage_inr_cr: 1200,
        area_impacted_sqkm: 86.5,
        transboundary_linkage: 'Western Ghats Eco-Fragile Escarpment',
        geotechnical_trigger: 'Structural detachment of topsoil along lateritic lithology slip plane on 42-degree slope.',
        official_ndma_report_ref: 'NDMA/SDRF-KER/2024/09-WYD',
        summary_description: 'Catastrophic midnight double debris flow originated from Vellarimala peak, transporting 8-meter boulders and wiping out 3 entire residential habitations, bridges, and tea plantations.'
      },
      {
        event_title: 'South Lhonak Glacial Lake Outburst Flood & Teesta Deluge',
        disaster_category: 'Glacial Lake Outburst Flood (GLOF)',
        primary_cause: 'Moraine Rim Liquefaction + Cloudburst Ice Avalanching',
        year: 2023,
        date_occurred: '2023-10-04',
        state_country: 'Sikkim (India / Tibet Transboundary Glacial Headwaters)',
        district_region: 'Mangan / Pakyong / Jalpaiguri',
        latitude: 27.9120,
        longitude: 88.2250,
        casualties_count: 179,
        displaced_population: 26000,
        economic_damage_inr_cr: 4500,
        area_impacted_sqkm: 142.0,
        transboundary_linkage: 'Tibet / High-Altitude Himalayan Cryosphere',
        geotechnical_trigger: 'Overtopping of terminal moraine dam triggered 50-million-cubic-meter surge into narrow gorge.',
        official_ndma_report_ref: 'NDMA/GLOF-SKM/2023/10',
        summary_description: 'Glacial flood surged down Teesta River at 40 km/h, totally disintegrating the 1200MW Chungthang Dam, washing away National Highway 10 and drowning military camps.'
      },
      {
        event_title: 'Joshimath Deep Structural Land Subsidence Crisis',
        disaster_category: 'Land Subsidence / Geotechnical Failure',
        primary_cause: 'Subsurface Aquifer Puncture + Heavy Construction on Ancient Glacial Scree',
        year: 2023,
        date_occurred: '2023-01-05',
        state_country: 'Uttarakhand (India)',
        district_region: 'Chamoli (Joshimath / Sunil / Manohar Bagh)',
        latitude: 30.5580,
        longitude: 79.5695,
        casualties_count: 0,
        displaced_population: 4200,
        economic_damage_inr_cr: 850,
        area_impacted_sqkm: 14.2,
        transboundary_linkage: 'Main Central Thrust (MCT) Himalayan Faultline',
        geotechnical_trigger: 'Unconsolidated glacial moraine scree lost shear resistance due to untreated civil wastewater percolation.',
        official_ndma_report_ref: 'NDMA/CBRI-UK/2023/JSH-01',
        summary_description: 'Rapid land sinking (up to 5.4 cm in 12 days mapped by ISRO Cartosat-2S) caused massive structural fissures across 868 residential buildings, forcing town-wide emergency evacuation.'
      },
      {
        event_title: 'Beas & Sutlej Himalayan Deluge & Highway Washouts',
        disaster_category: 'Flash Flood & Cloudburst',
        primary_cause: 'Western Disturbance Monsoon Convergence Extreme Precipitation',
        year: 2023,
        date_occurred: '2023-07-09',
        state_country: 'Himachal Pradesh (India)',
        district_region: 'Kullu / Mandi / Shimla / Kinnaur',
        latitude: 31.9579,
        longitude: 77.1095,
        casualties_count: 430,
        displaced_population: 34000,
        economic_damage_inr_cr: 10050,
        area_impacted_sqkm: 520.0,
        transboundary_linkage: 'Indus Basin Upper Mountain Catchment',
        geotechnical_trigger: 'Riverbed aggradation of 4-6m due to illegal muck dumping along steep gorge shoulders.',
        official_ndma_report_ref: 'NDMA/HP-DM/2023/FL-08',
        summary_description: 'Beas River surged to 1.5 lakh cusecs, sweeping multi-storey commercial hotels into the river, destroying 24 bridges and severing the main arterial highways for weeks.'
      },
      {
        event_title: 'Silchar Urban Embankment Breach Mega-Flood',
        disaster_category: 'Riverine Flood',
        primary_cause: 'Bethukandi Dyke Breach + Torrential Barak River Swell',
        year: 2022,
        date_occurred: '2022-06-20',
        state_country: 'Assam (India)',
        district_region: 'Cachar (Silchar)',
        latitude: 24.8333,
        longitude: 92.7789,
        casualties_count: 120,
        displaced_population: 280000,
        economic_damage_inr_cr: 1800,
        area_impacted_sqkm: 210.0,
        transboundary_linkage: 'Barak-Meghna River System (India-Bangladesh)',
        geotechnical_trigger: 'Man-made cutting of flood control dyke coupled with soil saturation failure.',
        official_ndma_report_ref: 'ASDMA/FLD-CACH/2022',
        summary_description: 'Submerged 90% of Silchar town under 10-15 feet of water for over 11 consecutive days; clean drinking water and food air-dropped by Indian Air Force helicopters.'
      },
      {
        event_title: 'Chamoli Ronti Glacier Rock Avalanche & Tapovan Disaster',
        disaster_category: 'Glacial Rock-Ice Avalanche & Flash Flood',
        primary_cause: 'Hanging Glacier Detachment from Ronti Peak (5,600m)',
        year: 2021,
        date_occurred: '2021-02-07',
        state_country: 'Uttarakhand (India)',
        district_region: 'Chamoli (Raini / Tapovan / Dhauliganga)',
        latitude: 30.4853,
        longitude: 79.6975,
        casualties_count: 204,
        displaced_population: 1500,
        economic_damage_inr_cr: 1500,
        area_impacted_sqkm: 65.0,
        transboundary_linkage: 'Nanda Devi Biosphere Alpine Permafrost Thawing',
        geotechnical_trigger: '27 million cubic meters of rock and ice free-fell 1,800m, converting into ultra-high-velocity pulverised debris slurry.',
        official_ndma_report_ref: 'DRDO-SASE/UK-2021/TAP',
        summary_description: 'Torrential slurry destroyed Rishiganga Hydro Project and entombed workers inside the Tapovan-Vishnugad tunnel system, washing away 5 border bridges.'
      },
      {
        event_title: 'Super Cyclone Amphan Deltaic Inundation',
        disaster_category: 'Tropical Super Cyclone & Storm Surge',
        primary_cause: 'Severe Low-Pressure Ocean Warming (Bay of Bengal)',
        year: 2020,
        date_occurred: '2020-05-20',
        state_country: 'West Bengal & Odisha (India) / Bangladesh',
        district_region: 'Sundarbans / South 24 Parganas / Kolkata',
        latitude: 21.6500,
        longitude: 88.3500,
        casualties_count: 128,
        displaced_population: 4400000,
        economic_damage_inr_cr: 102000,
        area_impacted_sqkm: 4500.0,
        transboundary_linkage: 'Ganga-Brahmaputra-Meghna Shared Delta (India/Bangladesh)',
        geotechnical_trigger: '5-meter storm surge breached over 160 kilometers of saline river embankments.',
        official_ndma_report_ref: 'NDMA/CYC-AMPHAN/2020',
        summary_description: 'Category 5 equivalent super cyclone with sustained 260 km/h gusts wrecked Kolkata and salted fertile agricultural lands across the Sundarbans for multiple seasons.'
      },
      {
        event_title: 'Great Kerala Floods & State-Wide Inundation',
        disaster_category: 'Severe Flood & Multiple Landslides',
        primary_cause: 'Continuous 164% Excess Monsoon Rain + Full Reservoir Sluice Releases',
        year: 2018,
        date_occurred: '2018-08-15',
        state_country: 'Kerala (India)',
        district_region: 'All 14 Districts (Aluva / Kuttanad / Idukki / Wayanad)',
        latitude: 10.1076,
        longitude: 76.3516,
        casualties_count: 483,
        displaced_population: 1450000,
        economic_damage_inr_cr: 31000,
        area_impacted_sqkm: 12000.0,
        transboundary_linkage: 'Arabian Sea Monsoon Trough System',
        geotechnical_trigger: 'Simultaneous opening of 35 state dams due to saturation capacity overflow.',
        official_ndma_report_ref: 'NDMA/KER-FLD/2018/FINAL',
        summary_description: 'Worst flood in Kerala in nearly a century. Entire towns submerged, Kochi International Airport closed under 4ft water, massive military and fishermen rescue operation.'
      },
      {
        event_title: 'Lalmatia Coal Mine Overburden Dump Disaster',
        disaster_category: 'Mining Geotechnical Collapse',
        primary_cause: 'Over-Steepened Waste Dump Slope + Poor Drainage Liquefaction',
        year: 2016,
        date_occurred: '2016-12-29',
        state_country: 'Jharkhand (India)',
        district_region: 'Godda (Rajmahal OCP / Lalmatia)',
        latitude: 25.0489,
        longitude: 87.3524,
        casualties_count: 23,
        displaced_population: 450,
        economic_damage_inr_cr: 120,
        area_impacted_sqkm: 2.8,
        transboundary_linkage: 'Gondwana Coal Basin Mining Belt',
        geotechnical_trigger: 'Circular shear failure of 350-meter-high waste rock pile exceeding natural angle of repose.',
        official_ndma_report_ref: 'DGMS/COAL-COLLAPSE/2016',
        summary_description: 'Massive overburden dump sliding down into deep pit, crushing heavy earthmoving machinery and entombing 23 miners under millions of cubic meters of rock.'
      },
      {
        event_title: 'Nepal Gorkha 7.8M Earthquake & Transboundary Tremors',
        disaster_category: 'Tectonic Earthquake & Avalanches',
        primary_cause: 'Indian Plate Under-Thrusting Eurasian Plate Fault Rupture',
        year: 2015,
        date_occurred: '2015-04-25',
        state_country: 'Nepal & India (Bihar / UP / West Bengal / Sikkim)',
        district_region: 'Gorkha / Kathmandu Valley / North Bihar Plains',
        latitude: 28.1470,
        longitude: 84.7080,
        casualties_count: 9000,
        displaced_population: 2800000,
        economic_damage_inr_cr: 75000,
        area_impacted_sqkm: 18000.0,
        transboundary_linkage: 'Main Himalayan Thrust (MHT) Fault System',
        geotechnical_trigger: 'Liquefaction of ancient lacustrine lake sediments and widespread rock avalanches.',
        official_ndma_report_ref: 'UN-OCHA/NDMA-IND-NEP/2015',
        summary_description: '7.8 magnitude earthquake killed 9,000+ in Nepal and 78 across Bihar and UP. Triggered deadly avalanche on Mount Everest and Langtang Valley landslide.'
      },
      {
        event_title: 'Malin Village Mudflow & Hillside Collapse',
        disaster_category: 'Catastrophic Soil Landslide',
        primary_cause: 'Deforestation for Padkai Agriculture + Relentless Rain',
        year: 2014,
        date_occurred: '2014-07-30',
        state_country: 'Maharashtra (India)',
        district_region: 'Pune (Ambegaon Taluka / Malin)',
        latitude: 19.1594,
        longitude: 73.6881,
        casualties_count: 151,
        displaced_population: 200,
        economic_damage_inr_cr: 45,
        area_impacted_sqkm: 1.5,
        transboundary_linkage: 'Western Ghats Basaltic Escarpment',
        geotechnical_trigger: 'Hill terracing cut away the toe of the slope; intense rain caused rapid pore-pressure fluidization.',
        official_ndma_report_ref: 'GSI/MAH-MALIN/2014',
        summary_description: 'At dawn, an entire mountain ridge disintegrated into a liquid mud tsunami, burying 44 houses and 151 people under 15 feet of mud in less than 3 minutes.'
      },
      {
        event_title: 'Jhelum River Mega-Inundation of Srinagar',
        disaster_category: 'Riverine Basin Inundation',
        primary_cause: 'Historic Rainfall Siltation + Loss of Natural Wetlands',
        year: 2014,
        date_occurred: '2014-09-07',
        state_country: 'Jammu & Kashmir (India) / Pakistan',
        district_region: 'Srinagar / Anantnag / Baramulla',
        latitude: 34.0837,
        longitude: 74.7973,
        casualties_count: 285,
        displaced_population: 1200000,
        economic_damage_inr_cr: 26000,
        area_impacted_sqkm: 850.0,
        transboundary_linkage: 'Indus / Jhelum Transboundary Basin',
        geotechnical_trigger: 'Siltation reduced Jhelum discharge capacity from 60,000 to only 28,000 cusecs.',
        official_ndma_report_ref: 'NDMA/JK-FLOOD/2014',
        summary_description: 'Srinagar city submerged under up to 20 feet of water. Over 80% of urban infrastructure, hospitals, and residential areas marooned for 16 days.'
      },
      {
        event_title: 'Kedarnath Glacial Lake Outburst & Himalayan Deluge',
        disaster_category: 'Multi-Hazard Flash Flood & Debris Flow',
        primary_cause: 'Chorabari Lake Moraine Breach + Multi-Day Cloudburst Convergence',
        year: 2013,
        date_occurred: '2013-06-16',
        state_country: 'Uttarakhand (India)',
        district_region: 'Rudraprayag / Chamoli / Uttarkashi',
        latitude: 30.7352,
        longitude: 79.0669,
        casualties_count: 5748,
        displaced_population: 110000,
        economic_damage_inr_cr: 14500,
        area_impacted_sqkm: 3800.0,
        transboundary_linkage: 'Mandakini / Alaknanda / Ganga Basin',
        geotechnical_trigger: 'Chorabari moraine lake dam collapse unleashed high-velocity wall of water and boulders.',
        official_ndma_report_ref: 'NDMA/UK-DELUGE/2013/FINAL',
        summary_description: 'India\'s most catastrophic modern mountain disaster. Thousands of pilgrims swept away along the Mandakini valley, totally pulverizing Rambara and Kedarnath township.'
      },
      {
        event_title: 'Sikkim 6.9M Earthquake & Rockfalls',
        disaster_category: 'Tectonic Earthquake',
        primary_cause: 'Himalayan Thrust Slip (Indo-Eurasian Boundary)',
        year: 2011,
        date_occurred: '2011-09-18',
        state_country: 'Sikkim (India) / Nepal / Tibet / Bhutan',
        district_region: 'North Sikkim / Gangtok / Mangan',
        latitude: 27.7200,
        longitude: 88.0600,
        casualties_count: 111,
        displaced_population: 45000,
        economic_damage_inr_cr: 2200,
        area_impacted_sqkm: 420.0,
        transboundary_linkage: 'Cross-Border Eastern Himalayas',
        geotechnical_trigger: 'Severe shaking activated 350+ synchronous landslides along steep road corridors.',
        official_ndma_report_ref: 'GSI/EQ-SKM/2011',
        summary_description: 'Strong shallow quake triggered immense boulders tumbling down slopes, slicing road links and destroying ancestral high-altitude monasteries.'
      },
      {
        event_title: 'Leh Ladakh Desert Cloudburst & Flash Mudflow',
        disaster_category: 'Arid Cloudburst Mudflow',
        primary_cause: 'Rare Mesoscale Convective Atmospheric Penetration',
        year: 2010,
        date_occurred: '2010-08-06',
        state_country: 'Ladakh / Jammu & Kashmir (India)',
        district_region: 'Leh (Choglamsar / Saboo)',
        latitude: 34.1526,
        longitude: 77.5771,
        casualties_count: 255,
        displaced_population: 9000,
        economic_damage_inr_cr: 280,
        area_impacted_sqkm: 45.0,
        transboundary_linkage: 'Indus Valley Cold Arid Trans-Himalayas',
        geotechnical_trigger: 'Vegetation-less granite scree instantly liquified into high-density slurry.',
        official_ndma_report_ref: 'IMD-NDMA/LEH-CB/2010',
        summary_description: '14 inches of rain fell on arid desert valley in under 2 hours, sweeping mud and debris into hospitals, homes, and military barracks at Choglamsar.'
      },
      {
        event_title: 'Kosi River Avulsion & Bihar Mega-Displacement',
        disaster_category: 'River Avulsion & Transboundary Embankment Breach',
        primary_cause: 'Breach of Kusaha Embankment in Nepal',
        year: 2008,
        date_occurred: '2008-08-18',
        state_country: 'Bihar (India) / Nepal',
        district_region: 'Supaul / Madhepura / Saharsa / Purnia',
        latitude: 26.5400,
        longitude: 86.9500,
        casualties_count: 527,
        displaced_population: 3300000,
        economic_damage_inr_cr: 4800,
        area_impacted_sqkm: 4500.0,
        transboundary_linkage: 'Kosi Transboundary Basin (Nepal-India)',
        geotechnical_trigger: 'River breached eastern embankment and permanently avulsed into an abandoned course 120 km east.',
        official_ndma_report_ref: 'CWC-NDMA/KOSI-AVULSION/2008',
        summary_description: '"Sorrow of Bihar" altered its geographic course overnight, marooning 3.3 million people across 5 districts that had not witnessed floods in over 50 years.'
      },
      {
        event_title: 'Kashmir 7.6M Transboundary Earthquake',
        disaster_category: 'Tectonic Earthquake',
        primary_cause: 'Subduction Uplift along Balakot-Bagh Fault',
        year: 2005,
        date_occurred: '2005-10-08',
        state_country: 'Jammu & Kashmir (India) / Pakistan',
        district_region: 'Uri / Tangdhar / Muzaffarabad',
        latitude: 34.4930,
        longitude: 73.6290,
        casualties_count: 87350,
        displaced_population: 3500000,
        economic_damage_inr_cr: 38000,
        area_impacted_sqkm: 30000.0,
        transboundary_linkage: 'Kashmir Transboundary Line of Control',
        geotechnical_trigger: 'Surface rupture length of 75 km with maximum vertical displacement of 5.5 meters.',
        official_ndma_report_ref: 'UN-MHA/EQ-KASH/2005',
        summary_description: 'Catastrophic earthquake wiped out Uri and Tangdhar border towns in India (1,400+ Indian casualties) and killed 86,000 across northern Pakistan.'
      },
      {
        event_title: 'Mumbai 944mm Cloudburst & Mithi River Overspill',
        disaster_category: 'Extreme Urban Deluge',
        primary_cause: 'Record 944 mm Rain in 24 Hours + High Tide Lock',
        year: 2005,
        date_occurred: '2005-07-26',
        state_country: 'Maharashtra (India)',
        district_region: 'Mumbai Metropolitan Region',
        latitude: 19.0760,
        longitude: 72.8777,
        casualties_count: 1094,
        displaced_population: 200000,
        economic_damage_inr_cr: 12500,
        area_impacted_sqkm: 430.0,
        transboundary_linkage: 'Arabian Sea Coastal Konkan Trough',
        geotechnical_trigger: 'Reclamation of Mithi river mudflats and destruction of mangrove swamps choked discharge.',
        official_ndma_report_ref: 'NDMA/MUMBAI-DELUGE/2005',
        summary_description: 'India\'s commercial capital brought to a complete standstill; thousands stranded in vehicles, local trains flooded to window levels, massive leptospirosis epidemic followed.'
      },
      {
        event_title: 'Indian Ocean Mega-Tsunami (Sumatra-Andaman 9.1M)',
        disaster_category: 'Undersea Earthquake & Tsunami',
        primary_cause: 'Megathrust Subduction of Indo-Australian Plate',
        year: 2004,
        date_occurred: '2004-12-26',
        state_country: 'Tamil Nadu / Andaman & Nicobar / Kerala / Andhra Pradesh (India)',
        district_region: 'Nagapattinam / Kanyakumari / Car Nicobar / Kollam',
        latitude: 3.3160,
        longitude: 95.8540,
        casualties_count: 16279,
        displaced_population: 647000,
        economic_damage_inr_cr: 11500,
        area_impacted_sqkm: 2200.0,
        transboundary_linkage: 'Trans-Oceanic Indian Ocean Rim (Indonesia, India, Sri Lanka, Thailand)',
        geotechnical_trigger: '1,300 km seafloor rupture pushed trillions of tons of seawater at jetliner speeds.',
        official_ndma_report_ref: 'GOI-MHA/TSUNAMI-REPORT/2004',
        summary_description: 'Deadliest tsunami in world history. 30-foot tsunami waves wiped out coastal fishing hamlets in Nagapattinam, severed Andaman & Nicobar communication, led to formation of NDMA.'
      }
    ];

    const insertDisaster20 = db.prepare(`
      INSERT INTO historical_disasters_20yr (
        event_title, disaster_category, primary_cause, year, date_occurred,
        state_country, district_region, latitude, longitude, casualties_count,
        displaced_population, economic_damage_inr_cr, area_impacted_sqkm,
        transboundary_linkage, geotechnical_trigger, official_ndma_report_ref,
        summary_description
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    for (const d of historicalDisasters) {
      insertDisaster20.run(
        d.event_title, d.disaster_category, d.primary_cause, d.year, d.date_occurred,
        d.state_country, d.district_region, d.latitude, d.longitude, d.casualties_count,
        d.displaced_population, d.economic_damage_inr_cr, d.area_impacted_sqkm,
        d.transboundary_linkage, d.geotechnical_trigger, d.official_ndma_report_ref,
        d.summary_description
      );
    }
    console.log(`[Govt Seed] Seeded ${historicalDisasters.length} 20-Year Historical Disaster records.`);
  }

  // 4. GEOTECHNICAL SOIL & ROCK LITHOLOGY DATASET (GSI / SLUSI / ICAR)
  const soilCount = db.prepare('SELECT count(*) as count FROM geological_soil_rock').get().count;
  if (soilCount === 0) {
    const soilRockData = [
      {
        region_name: 'Himalayan High Alpine Tectonic Scree Belt',
        district: 'Chamoli / Rudraprayag / Uttarkashi',
        state: 'Uttarakhand',
        soil_major_type: 'Mountain Scree & Moraine Lithosol (Inceptisol)',
        soil_sub_type: 'Unconsolidated Glacial Moraine & Colluvium',
        soil_depth_class: 'Shallow to Very Shallow (0.2m - 1.2m)',
        permeability_rate: 'High (Rapid Drainage into Scree)',
        internal_friction_angle_deg: 34.0,
        cohesion_kpa: 8.5,
        liquefaction_susceptibility: 'Moderate upon Water Saturation',
        rock_system: 'Central Himalayan Crystalline Complex',
        lithology_description: 'High-grade metamorphic sequence consisting of garnetiferous mica schist, tourmaline granite, and biotite gneiss.',
        dominant_rock_types: 'Mica Schist, Quartzite, Calc-Silicate, Gneiss',
        structural_faultlines: 'Main Central Thrust (MCT) & Vaikrita Thrust Zone',
        seismic_zone: 'Zone V (Very High Damage Risk)',
        slope_stability_index: 38.0,
        weathering_degree: 'Intense Mechanical & Freeze-Thaw Wedging',
        recommended_foundation_type: 'Deep Micropiles anchored to Fresh Crystalline Bedrock; No shallow spread footings on scree.'
      },
      {
        region_name: 'Western Ghats Lateritic Escarpment',
        district: 'Wayanad / Idukki / Malappuram',
        state: 'Kerala',
        soil_major_type: 'Tropical Laterite (Ultisol / Oxisol)',
        soil_sub_type: 'Ferruginous Vesicular Pisolitic Laterite',
        soil_depth_class: 'Deep to Very Deep (1.5m - 5.0m)',
        permeability_rate: 'Moderate to High in Topsoil, Low at Clay Horizon',
        internal_friction_angle_deg: 26.5,
        cohesion_kpa: 22.0,
        liquefaction_susceptibility: 'High (Pore Pressure Burst Collapse)',
        rock_system: 'Charnockite & Khondalite Archaean Peninsular Gneiss',
        lithology_description: 'Ancient precambrian deep-crustal granulite facies with pyroxene granulites and hornblende-biotite gneisses.',
        dominant_rock_types: 'Charnockite, Biotite Gneiss, Hornblende Gneiss',
        structural_faultlines: 'Bhavani Shear Zone & Moyar Shear System',
        seismic_zone: 'Zone III (Moderate Damage Risk)',
        slope_stability_index: 44.0,
        weathering_degree: 'Deep Spheroidal & Chemical Leaching (Saprolite >10m)',
        recommended_foundation_type: 'Step-terraced reinforced concrete piers penetrating below the lithomargic clay layer.'
      },
      {
        region_name: 'Brahmaputra Active Riverine Alluvial Plain',
        district: 'Majuli / Dhemaji / Morigaon',
        state: 'Assam',
        soil_major_type: 'Active Alluvial Floodplain Silt (Khadar)',
        soil_sub_type: 'Fine Silty Loam & Micaceous Sand (Entisols)',
        soil_depth_class: 'Very Deep (>25m)',
        permeability_rate: 'High (Rapid Seepage / Scour Prone)',
        internal_friction_angle_deg: 29.0,
        cohesion_kpa: 12.0,
        liquefaction_susceptibility: 'Critical (High Liquefaction Risk during Quakes)',
        rock_system: 'Quaternary Indo-Brahmaputra Alluvium',
        lithology_description: 'Unconsolidated layered sands, silts, and soft plastic clays deposited over down-faulted crystalline basement.',
        dominant_rock_types: 'Uncemented Silty Sand, Fluvial River Gravels',
        structural_faultlines: 'Dauki Fault & Brahmaputra Regional Thrust',
        seismic_zone: 'Zone V (Extreme Seismic Vulnerability)',
        slope_stability_index: 52.0,
        weathering_degree: 'Chemical Decomposition of Feldspathic Silts',
        recommended_foundation_type: 'Elevated Concrete Stilt / Chang-Ghar Platforms with Geo-synthetic Matting.'
      },
      {
        region_name: 'Deccan Traps Basaltic Plateau',
        district: 'Pune / Raigad / Satara',
        state: 'Maharashtra',
        soil_major_type: 'Black Cotton Soil (Regur / Vertisol)',
        soil_sub_type: 'Deep Montmorillonite Heavy Swell-Shrink Clay',
        soil_depth_class: 'Moderate (0.8m - 2.5m)',
        permeability_rate: 'Very Low (Impermeable upon Swelling)',
        internal_friction_angle_deg: 16.0,
        cohesion_kpa: 48.0,
        liquefaction_susceptibility: 'Low',
        rock_system: 'Deccan Traps Continental Flood Basalts',
        lithology_description: 'Sub-horizontal thick lava flows of tholeiitic basalt with columnar jointing, inter-trappean red bole beds, and vesicular horizons.',
        dominant_rock_types: 'Compact Basalt, Amygdaloidal Basalt, Volcanic Breccia',
        structural_faultlines: 'West Coast Fault & Koyna Seismic Zone',
        seismic_zone: 'Zone IV (High Damage Risk in Escarpments)',
        slope_stability_index: 68.0,
        weathering_degree: 'Moderate Mechanical Joint Exfoliation; Weathered Red Boles serve as slip planes.',
        recommended_foundation_type: 'Under-Reamed Piles resting directly on Hard Compact Basalt stratum.'
      },
      {
        region_name: 'Gondwana Coal Basin & Sedimentary Formations',
        district: 'Dhanbad / Bokaro / Angul / Korba',
        state: 'Jharkhand / Odisha / Chhattisgarh',
        soil_major_type: 'Red Sandy Loam & Mine Spoils (Alfisols)',
        soil_sub_type: 'Ferruginous Loamy Sand with Carbonaceous Overburden',
        soil_depth_class: 'Shallow in Opencast zones (0.5m - 1.8m)',
        permeability_rate: 'Moderate',
        internal_friction_angle_deg: 31.0,
        cohesion_kpa: 18.0,
        liquefaction_susceptibility: 'Low',
        rock_system: 'Lower Gondwana Damuda Group (Barakar Formation)',
        lithology_description: 'Cyclic sedimentary sequence of coarse felspathic sandstones, carbonaceous shales, fireclays, and bituminous coal seams.',
        dominant_rock_types: 'Barakar Sandstone, Carbonaceous Shale, Coal Seams',
        structural_faultlines: 'Damodar Valley Graben Boundary Faults',
        seismic_zone: 'Zone III (Moderate Risk)',
        slope_stability_index: 55.0,
        weathering_degree: 'High Chemical Weathering of Shales leading to slaking and rockfalls.',
        recommended_foundation_type: 'Compacted Engineered Backfill with Grouting over Void Subsidence areas.'
      },
      {
        region_name: 'Indo-Gangetic Deep Alluvial Trench',
        district: 'Varanasi / Patna / Gorakhpur',
        state: 'Uttar Pradesh / Bihar',
        soil_major_type: 'Old Alluvial Soil (Bhangar - Inceptisols)',
        soil_sub_type: 'Clayey Loam with Calcareous Kankar Nodules',
        soil_depth_class: 'Extremely Deep (>50m)',
        permeability_rate: 'Low to Moderate',
        internal_friction_angle_deg: 24.0,
        cohesion_kpa: 35.0,
        liquefaction_susceptibility: 'Moderate along saturated riverbanks',
        rock_system: 'Quaternary Indo-Gangetic Foredeep',
        lithology_description: 'Dense sedimentary infill of clay, silt, fine sand, and calcareous lime concretions (Kankar).',
        dominant_rock_types: 'Consolidated Alluvium, Siltstone',
        structural_faultlines: 'Himalayan Frontal Thrust (HFT) Blind Faults',
        seismic_zone: 'Zone IV (High Risk across North Bihar)',
        slope_stability_index: 74.0,
        weathering_degree: 'Low',
        recommended_foundation_type: 'Raft Foundation or Friction Piles.'
      },
      {
        region_name: 'Eastern Coastal Deltaic Marine Clays',
        district: 'Puri / Kendrapara / South 24 Parganas',
        state: 'Odisha / West Bengal',
        soil_major_type: 'Coastal Saline & Marine Clays (Salids)',
        soil_sub_type: 'Halomorphic Plastic Estuarine Mud',
        soil_depth_class: 'Deep (>15m)',
        permeability_rate: 'Very Low',
        internal_friction_angle_deg: 12.0,
        cohesion_kpa: 25.0,
        liquefaction_susceptibility: 'High under Storm Surge Cyclic Loading',
        rock_system: 'Quaternary-Holocene Deltaic Sediments',
        lithology_description: 'Inter-tidal clays, organic peats, fine deltaic sands with high groundwater table at 0.5m depth.',
        dominant_rock_types: 'Organic Peat Beds, Soft Marine Clays, Silt',
        structural_faultlines: 'Bengal Basin Deep Basement Hinge Line',
        seismic_zone: 'Zone III / IV',
        slope_stability_index: 48.0,
        weathering_degree: 'Intense Saline Degradation & Coastal Tidal Scour',
        recommended_foundation_type: 'Bored Cast-in-situ Friction Piles with Sulphate-Resistant Cement.'
      },
      {
        region_name: 'Thar Desert Sand Dunes & Arid Calc-Silicate',
        district: 'Jaisalmer / Bikaner / Nagaur',
        state: 'Rajasthan',
        soil_major_type: 'Arid Desert Sand (Aridisols / Psamments)',
        soil_sub_type: 'Aeolian Fine Quartz Sand with Gypsiferous Layers',
        soil_depth_class: 'Deep shifting sand (0.5m - 20m)',
        permeability_rate: 'Very High',
        internal_friction_angle_deg: 32.0,
        cohesion_kpa: 2.0,
        liquefaction_susceptibility: 'Zero (Dry) / High (if flash flooded)',
        rock_system: 'Marwar Supergroup & Vindhyan Sandstone',
        lithology_description: 'Fine-grained quartzitic red sandstones, limestones, and dolomites resting on Malani Igneous Suite.',
        dominant_rock_types: 'Jodhpur Sandstone, Marble, Limestone',
        structural_faultlines: 'Luni-Sukri Lineament & Great Boundary Fault',
        seismic_zone: 'Zone II / III',
        slope_stability_index: 82.0,
        weathering_degree: 'Intense Wind Deflation & Thermal Expansion',
        recommended_foundation_type: 'Shallow Spread Footings on Compacted Kankar hardpan or Calcrete.'
      }
    ];

    const insertSoil = db.prepare(`
      INSERT INTO geological_soil_rock (
        region_name, district, state, soil_major_type, soil_sub_type,
        soil_depth_class, permeability_rate, internal_friction_angle_deg,
        cohesion_kpa, liquefaction_susceptibility, rock_system, lithology_description,
        dominant_rock_types, structural_faultlines, seismic_zone, slope_stability_index,
        weathering_degree, recommended_foundation_type
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    for (const s of soilRockData) {
      insertSoil.run(
        s.region_name, s.district, s.state, s.soil_major_type, s.soil_sub_type,
        s.soil_depth_class, s.permeability_rate, s.internal_friction_angle_deg,
        s.cohesion_kpa, s.liquefaction_susceptibility, s.rock_system, s.lithology_description,
        s.dominant_rock_types, s.structural_faultlines, s.seismic_zone, s.slope_stability_index,
        s.weathering_degree, s.recommended_foundation_type
      );
    }
    console.log(`[Govt Seed] Seeded ${soilRockData.length} Geotechnical Soil and Rock records.`);
  }

  console.log('[Govt Seed] Government registries seeded successfully.');
}

if (require.main === module) {
  seedGovtData();
}

module.exports = { seedGovtData };
